services:
  - type: web
    name: sr-bazaar
    env: python
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
