databases:
  - name: postgresql
    databaseName: srbazaar
    user: srbazaar
    plan: free

services:
  - type: web
    name: sr-bazaar
    env: python
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput
    
    # Run migrations as part of the start command
    startCommand: >
      python manage.py migrate --noinput && \
      gunicorn ecommerce.wsgi:application
    
    # Database URL will be automatically injected by Render
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings.production
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DISABLE_COLLECTSTATIC
        value: 1
